sudo: required

dist: trusty

jobs:
  include:
    - if: tag IS present
      stage: build docker image
      script:
        - docker build -t e2e-container .
        - docker tag e2e-container skyapm/e2e-container:${TRAVIS_TAG}
        - docker images
