sudo: required

dist: trusty

jobs:
  include:
    - stage: try build docker images
      script:
        - docker build -f Dockerfile-JDK8 -t e2e-container:jdk8 .
        - docker build -f Dockerfile-JDK9 -t e2e-container:jdk9 .
        - docker build -f Dockerfile-JDK11 -t e2e-container:jdk11 .
        - docker build -f Dockerfile-JDK12 -t e2e-container:jdk12 .
        - docker images

    - if: tag IS present
      stage: build and deploy docker image for JDK8
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -f Dockerfile-JDK8 -t e2e-container-jdk8 .
        - docker tag e2e-container-jdk8 skyapm/e2e-container:jdk8-${TRAVIS_TAG}
        - docker images
        - docker push skyapm/e2e-container:jdk8-${TRAVIS_TAG}

    - if: tag IS present
      stage: build and deploy docker image for JDK9
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -f Dockerfile-JDK9 -t e2e-container-jdk9 .
        - docker tag e2e-container-jdk9 skyapm/e2e-container:jdk9-${TRAVIS_TAG}
        - docker images
        - docker push skyapm/e2e-container:jdk9-${TRAVIS_TAG}

    - if: tag IS present
      stage: build and deploy docker image for JDK11
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -f Dockerfile-JDK11 -t e2e-container-jdk11 .
        - docker tag e2e-container-jdk11 skyapm/e2e-container:jdk11-${TRAVIS_TAG}
        - docker images
        - docker push skyapm/e2e-container:jdk11-${TRAVIS_TAG}

    - if: tag IS present
      stage: build and deploy docker image for JDK12
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -f Dockerfile-JDK12 -t e2e-container-jdk12 .
        - docker tag e2e-container-jdk12 skyapm/e2e-container:jdk12-${TRAVIS_TAG}
        - docker images
        - docker push skyapm/e2e-container:jdk12-${TRAVIS_TAG}
